// <auto-generated />
using System;
using Dice.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DDA_Server.Migrations
{
    [DbContext(typeof(DiceContext))]
    [Migration("20240116152236_AddInterpretationToDiceSpread4")]
    partial class AddInterpretationToDiceSpread4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dice.Entities.DiceSpread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("D10_100")
                        .HasColumnType("integer");

                    b.Property<int>("D12")
                        .HasColumnType("integer");

                    b.Property<int>("D2")
                        .HasColumnType("integer");

                    b.Property<int>("D20")
                        .HasColumnType("integer");

                    b.Property<int>("D4")
                        .HasColumnType("integer");

                    b.Property<int>("D6")
                        .HasColumnType("integer");

                    b.Property<int>("D8")
                        .HasColumnType("integer");

                    b.Property<string>("Dalle3ImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Interpretation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LunarData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DiceSpread");
                });
#pragma warning restore 612, 618
        }
    }
}
